version: '3'
services:
    app:
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/var/www/localhost/htdocs/'
        networks:
            - mvc
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'app'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'password'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
#            - './db/conf/my.cnf:/etc/my.cnf'
        networks:
            - mvc
    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - "8080:8080"
        environment:
            ADMINER_DESIGN: pepa-linha
            ADMINER_PLUGINS: tables-filter
        networks:
            - mvc

networks:
    mvc:
        driver: bridge
volumes:
    mvcdb:
        driver: local
