<!doctype html>
<html lang="cs">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Chyba</title>
	<style>
		body {
			margin: 0;
			padding: 0;
			background-color: #f5f5f5;
			font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
			font-size: 14px;
			line-height: 1.42857143;
			color: #b60000;
			height: 100vh;
			display: flex;
			flex-direction: column;
			align-items: center;
			justify-content: center;
			text-align: center;
		}

		h1 {
			font-size: 3rem;
			font-weight: 500;
			line-height: 1.1;
			color: inherit;
			margin-top: 0;
			margin-bottom: 20px;
		}

		h2 {
			font-size: 2rem;
			font-weight: 500;
			line-height: 1.1;
			color: inherit;
			margin-top: 0;
			margin-bottom: 20px;
		}

		p {
			font-size: 1.5rem;
			margin: 0 0 10px;
		}

	</style>
</head>
<body>
<h1>
	Server vrátil kód <?= $code ?>
</h1>
<h2>
    <?= $message ?>
</h2>
<a href="<?= $this->route('home') ?>">Zpět na úvodní stránku</a>
</body>
</html>