<section>
	<article class="w-full max-w-md bg-white rounded-lg shadow-md p-8 mx-auto">
		<h2 class="text-2xl font-bold text-center text-blue-600 mb-6">User <?= $user->getUsername() ?> is logged in</h2>
		<a href="<?= $this->route('logout') ?>" class="w-full bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-400">
			Logout
		</a>
	</article>
</section>